Output aliaser_demo.gif

Set Height 1000
Set Width 1600

Type "source ../aliaser.sh"
Sleep 500ms
Enter
Sleep 2s
Type "aliaser help"
Sleep 500ms
Enter
Sleep 8s

Hide
Type "aliaser clearall"
Enter
Show

Ctrl+L

Type "aliaser"
Sleep 500ms
Enter
Sleep 2s
Type "aliaser list"
Sleep 500ms
Enter
Sleep 2s

Ctrl+L

Type `aliaser "sayhi='echo hello'"`
Sleep 500ms
Enter
Sleep 4s
Type "sayhi"
Sleep 500ms
Enter
Sleep 4s

Type "aliaser list"
Sleep 500ms
Enter
Sleep 8s

Ctrl+L

